# Generated by Django 5.0.1 on 2024-07-06 17:27

from django.db import migrations, IntegrityError

def create_initial_model_names(apps, schema_editor):
    ModelName = apps.get_model('model_manager', 'ModelName')
    models = [
        {"name": "gpt-4", "code": 1, "provider": "OpenAI"},
        {"name": "gpt-4-turbo", "code": 2, "provider": "OpenAI"},
        {"name": "gpt-3.5-turbo", "code": 3, "provider": "OpenAI"},
        {"name": "text-embedding-3-large", "code": 4, "provider": "OpenAI"},
        {"name": "text-embedding-3-small", "code": 5, "provider": "OpenAI"},
    ]
    for model in models:
        try:
            ModelName.objects.create(**model)
        except IntegrityError as e:
            print(f"Failed to create model: {model}. Error: {e}")
            
class Migration(migrations.Migration):

    dependencies = [
        ('model_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_model_names)
    ]
